### ISSUE TITLE
 loot Log not captured

### ISSUE THREAD

**Issue by nullpointer2017** [kalilistic/Kapture#25]
Log not captured　in Eden's Verse: Fulmination (Savage) 
I don't know because I haven't tried it in other Eden areas.
The other dungeons before and after got the log correctly.
ACT log shows a loot.
![actlog](https://user-images.githubusercontent.com/28534413/75805363-0a3e0a80-5dc5-11ea-94b0-467eb177ebd4.png)
i use Japanese version FFXIV.
Kapture version is  1.0.9

![kapusetting](https://user-images.githubusercontent.com/28534413/75805384-14f89f80-5dc5-11ea-8afb-c87b3a02bb4f.png)

**Comment by kalilistic** [comment]
Hi - will confirm. Can you provide text from ACT logs instead of image?

**Comment by nullpointer2017** [comment]
advanced filter 
![kapu3](https://user-images.githubusercontent.com/28534413/75844213-ae9d6c80-5e18-11ea-8863-a53a0e3d74b7.png)

Only "共通アイテムを除外する" is set.

I sent the ACT log by DM of discord, is it OK?
I don't want to upload it to public places because it contains character names and chat content.

**Comment by kalilistic** [comment]
Advanced filter looks okay.  Don't need the whole log. Just the lines you already showed in text format.

**Comment by nullpointer2017** [comment]
I see. I understand.
Attach the log.
[act.log](https://github.com/kalilistic/Kapture/files/4285472/act.log)

**Comment by nullpointer2017** [comment]
Additional Information

I went to "Eden's Verse: Furor (Savage)" today and found that "超耐久型トームストーン" and "衛兵団の硬化薬" were logging correctly.
but, the concurrent drops "エデンコーラス・ヘッドギアチェスト【ILv500】" and "エデンコーラス・ハンドギアチェスト【ILv500】" were not logged.

**Comment by kalilistic** [comment]
I'm having trouble reproducing this so far. Any errors in these files?
C:\Users\username\AppData\Roaming\Advanced Combat Tracker\Kapture.log
C:\Users\username\AppData\Roaming\Advanced Combat Tracker\Advanced Combat Tracker.log

**Comment by nullpointer2017** [comment]
No, I could not check the log which seems to be an error.

**Comment by nullpointer2017** [comment]
in Aetherbridge 

It seems that 500 of "【ILv500】" is parsed as the quantity.

![kapudebug](https://user-images.githubusercontent.com/28534413/76158300-e6c5e780-6157-11ea-8e46-edb870cf9090.png)

**Comment by kalilistic** [comment]
Great work, @nullpointer2017 ! Thank you for looking into this. I pushed a new beta and this issue should now be fixed. You can download the beta release directly or ensure beta releases are enabled (ベータ版を確認する). Please let me know if you still see any issues.

**Comment by nullpointer2017** [comment]
Verified that the log was retrieved correctly.
Thank you for the  fix.
