### ISSUE TITLE
Item Filter not working

### ISSUE THREAD

**Issue by ltel77** [kalilistic/Kapture#44]
My install of Kapture has a webhook attached to a discord channel. I have both exclude common items and High-End Duty only checked. When I desynth 3 items while in the Pendants Inn in  the Crystarium and Kapture recorded the crystals I acquired and passed into discord. A couple of minutes later when I completed a Custom Deliveries weekly challenge log in Rhalgr's Reach, it seemed to have recorded in the discord webhook that I obtained "Gil x1000"

![Kapture Issue](https://user-images.githubusercontent.com/15847629/89111352-d96d0a80-d422-11ea-9e07-29cc5f6a537b.png)

Edit:
I've desynth items before in the inn as well as open areas and received gil from logs before without Kapture recording. Settings haven't change on Kapture plugin since initial install for Savage Loot recording.

**Comment by kalilistic** [comment]
Hi - are you using the current beta? I fixed an issue with the filters recently. If not, you can select "Check for Beta" checkbox and restart ACT.

**Comment by kalilistic** [comment]
I take that back. Just re-tested and the Zone Filter (High-End Duty Only) wasn't working when in outside of raids/dungeons. I just pushed a new beta release. You can download per instructions above or just download from here: https://github.com/kalilistic/Kapture/releases/tag/v1.1.7.

**Comment by ltel77** [comment]
Tested in both Rhalgr's Reach and Crystarium. Filter is working again. Thanks again!

Love this plugin. Make loot tracking in raid so much easier for our static
